# Generated by Django 3.2.5 on 2021-07-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superheroes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superhero',
            name='rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
